import assert from 'node:assert/strict';
import { encodeSnapshot, decodeSnapshot } from '@/lib/snapshotCodec';
import { DEFAULT_SNAPSHOT } from '@/lib/snapshotTypes';
import { DEFAULT_INCOME_SUMMARY_INPUT } from '@/lib/incomeSummaryCalculator';
assert.equal(encodeSnapshot(DEFAULT_SNAPSHOT), 'N4IgbiBcCMC+Q', 'mặc định chỉ có version');
const snap = structuredClone(DEFAULT_SNAPSHOT) as any;
snap.tabs.vat = { ...snap.tabs.vat, salesRevenue: 123_000_000 };
snap.tabs.severance = { ...snap.tabs.severance, averageSalary: 25_000_000 };
snap.tabs.mortgage = { ...snap.tabs.mortgage, propertyPrice: 4_500_000_000 };
snap.tabs.multiSourceIncome = { ...snap.tabs.multiSourceIncome, dependents: 2 };
snap.tabs.incomeSummary = { ...DEFAULT_INCOME_SUMMARY_INPUT, entries: [{ id: 'e1', category: 'salary', description: 'Lương', amount: 30_000_000, month: 3 }] };
const dec = decodeSnapshot(encodeSnapshot(snap))! as any;
assert.equal(dec.tabs.vat.salesRevenue, 123_000_000, 'vat');
assert.equal(dec.tabs.severance.averageSalary, 25_000_000, 'severance');
assert.equal(dec.tabs.mortgage.propertyPrice, 4_500_000_000, 'mortgage');
assert.equal(dec.tabs.multiSourceIncome.dependents, 2, 'multiSource');
assert.equal(dec.tabs.incomeSummary.entries[0].amount, 30_000_000, 'incomeSummary');
assert.equal(dec.tabs.incomeSummary.entries[0].description, 'Lương');
console.log('SHARE TABS OK, len', encodeSnapshot(snap).length);
